const Items =[
    { 
        "id": 1,
        "item_name": "Language Arts",
        "item_image": "images/arts.png",
        "price": 79,
        "qty": 7,
        "location": "London",
    },
    { 
        "id": 2,
        "item_name": "Advanced Calculus",
        "item_image": "images/calculus.png",
        "price": 109,
        "qty": 10,
        "location": "Reading",
    },
    { 
        "id": 3,
        "item_name": "English",
        "item_image": "images/english.png",
        "price": 39,
        "qty": 5,
        "location": "London",
    },
    { 
        "id": 4,
        "item_name": "Mathematics Level 5",
        "item_image": "images/maths.png",
        "price": 39,
        "qty": 5,
        "location": "London",
    },
    {
        "id": 5,
        "item_name": "Web Development",
        "item_image": "images/webdevelopment.png",
        "price": 99,
        "qty": 8,
        "location": "London",
    },
    {
        "id": 6,
        "item_name": "Data Science Essentials",
        "item_image": "images/datascience.png",
        "price": 129,
        "qty": 12,
        "location": "Manchester",
    },
    {
        "id": 7,
        "item_name": "Mobile App Development",
        "item_image": "images/mobileappdevelopment.png",
        "price": 79,
        "qty": 6,
        "location": "Birmingham",
    },
    {
        "id": 8,
        "item_name": "Network Security",
        "item_image": "images/networksecurity.png",
        "price": 109,
        "qty": 6,
        "location": "Bristol",
    },
    {
        "id": 9,
        "item_name": "Cloud Computing",
        "item_image": "images/cloudcomputing.png",
        "price": 89,
        "qty": 7,
        "location": "Oxford",
    },
    {
        "id": 10,
        "item_name": "Artificial Intelligence",
        "item_image": "images/artificialintelligence.png",
        "price": 119,
        "qty": 11,
        "location": "Cambridge",
    },
    {
        "id": 11,
        "item_name": "Cybersecurity Fundamentals",
        "item_image": "images/cybersecurity.png",
        "price": 119,
        "qty": 10,
        "location": "Manchester",
    },
    {
        "id": 12,
        "item_name": "Database Management",
        "item_image": "images/no-itemimage.png",
        "price": 79,
        "qty": 9,
        "location": "Brighton",
    },
    {
        "id": 13,
        "item_name": "DevOps Practices",
        "item_image": "images/no-itemimage.png",
        "price": 109,
        "qty": 8,
        "location": "London",
    },
    {
        "id": 14,
        "item_name": "Biology",
        "item_image": "images/no-itemimage.png",
        "price": 89,
        "qty": 8,
        "location": "Manchester",
    },
    {
        "id": 15,
        "item_name": "Physics",
        "item_image": "images/no-itemimage.png",
        "price": 129,
        "qty": 12,
        "location": "Oxford",
    },
    {
        "id": 16,
        "item_name": "History",
        "item_image": "images/no-itemimage.png",
        "price": 49,
        "qty": 6,
        "location": "Birmingham",
    },
    {
        "id": 17,
        "item_name": "Chemistry Level 5",
        "item_image": "images/no-itemimage.png",
        "price": 49,
        "qty": 6,
        "location": "Bristol",
    },
    {
        "id": 18,
        "item_name": "Geography",
        "item_image": "images/no-itemimage.png",
        "price": 69,
        "qty": 7,
        "location": "London",
    },
    {
        "id": 19,
        "item_name": "Computer Science",
        "item_image": "images/no-itemimage.png",
        "price": 99,
        "qty": 11,
        "location": "Cambridge",
    },
    {
        "id": 20,
        "item_name": "Literature",
        "item_image": "images/no-itemimage.png",
        "price": 59,
        "qty": 9,
        "location": "Brighton",
    },
    {
        "id": 21,
        "item_name": "Mathematics Level 7",
        "item_image": "images/maths.png",
        "price": 59,
        "qty": 9,
        "location": "London",
    },
    {
        "id": 22,
        "item_name": "Cybersecurity Fundamentals",
        "item_image": "images/no-itemimage.png",
        "price": 119,
        "qty": 10,
        "location": "Manchester",
    }
]